[phases.setup]
nixPkgs = ["php82", "nodejs_20", "npm"]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate:fresh --seed --force --database=mysql && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}"
